import React from 'react';
import { motion } from 'framer-motion';
import { useReports } from '../../context/ReportsContext';
import { Eye, Download, Share2, FileCode, CheckCircle, RefreshCw, AlertTriangle } from 'lucide-react';

export function ReportsTable() {
  const {
    reports,
    selectedIds,
    toggleSelect,
    openPreview,
    setShareReport,
    setExportReport,
  } = useReports();

  const getStatusBadge = (status) => {
    if (status === 'ready') {
      return (
        <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold border bg-emerald-500/10 border-emerald-500/20 text-emerald-400">
          <CheckCircle className="w-2.5 h-2.5" />
          Ready
        </span>
      );
    }
    if (status === 'processing') {
      return (
        <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold border bg-brand-blue/10 border-brand-blue/20 text-brand-blue">
          <RefreshCw className="w-2.5 h-2.5 animate-spin" />
          Processing
        </span>
      );
    }
    return (
      <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold border bg-red-500/10 border-red-500/20 text-red-400">
        <AlertTriangle className="w-2.5 h-2.5" />
        Failed
      </span>
    );
  };

  const getScoreColor = (score) => {
    if (score >= 90) return 'text-emerald-400';
    if (score >= 80) return 'text-amber-400';
    return 'text-red-400';
  };

  return (
    <div className="w-full overflow-x-auto rounded-xl border border-white/[0.08] bg-white/[0.01]">
      <table className="w-full text-left border-collapse min-w-[1000px] select-none">
        <thead>
          <tr className="border-b border-white/[0.08] bg-white/[0.02] text-[10px] font-bold uppercase tracking-wider text-brand-text-secondary">
            <th className="py-3 px-4 w-10">Select</th>
            <th className="py-3 px-4">Report Name</th>
            <th className="py-3 px-4">Repository</th>
            <th className="py-3 px-4">Branch</th>
            <th className="py-3 px-4">Generated By</th>
            <th className="py-3 px-4">Generated At</th>
            <th className="py-3 px-4 text-center">Quality Score</th>
            <th className="py-3 px-4">Status</th>
            <th className="py-3 px-4 text-center">Version</th>
            <th className="py-3 px-4 text-right">Actions</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-white/[0.05]">
          {reports.length === 0 ? (
            <tr>
              <td colSpan="10" className="py-12 text-center text-xs text-brand-text-secondary font-medium">
                No reports generated yet.
              </td>
            </tr>
          ) : (
            reports.map((r, idx) => {
              const isSelected = selectedIds.includes(r.id);
              const isFailed = r.status === 'failed';
              const isProcessing = r.status === 'processing';

              return (
                <motion.tr
                  key={r.id}
                  initial={{ opacity: 0, y: 4 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: Math.min(idx * 0.015, 0.3) }}
                  className={`hover:bg-white/[0.02] transition-colors cursor-pointer group ${
                    isSelected ? 'bg-brand-blue/[0.015]' : ''
                  }`}
                  onClick={() => !isFailed && !isProcessing && openPreview(r)}
                >
                  {/* Select */}
                  <td className="py-3.5 px-4" onClick={(e) => e.stopPropagation()}>
                    <input
                      type="checkbox"
                      checked={isSelected}
                      disabled={isFailed || isProcessing}
                      onChange={() => toggleSelect(r.id)}
                      className="rounded border-white/[0.15] bg-white/[0.02] text-brand-blue focus:ring-brand-blue/30 w-3.5 h-3.5 cursor-pointer disabled:opacity-20 disabled:cursor-not-allowed"
                    />
                  </td>

                  {/* Name */}
                  <td className="py-3.5 px-4 max-w-[220px]">
                    <div className="font-bold text-xs text-white group-hover:text-brand-blue transition-colors truncate">
                      {r.name}
                    </div>
                  </td>

                  {/* Repo */}
                  <td className="py-3.5 px-4 text-xs font-semibold text-white/90">
                    <span className="font-mono">{r.repo}</span>
                  </td>

                  {/* Branch */}
                  <td className="py-3.5 px-4 text-xs text-brand-text-secondary font-mono">
                    {r.branch}
                  </td>

                  {/* Generated By */}
                  <td className="py-3.5 px-4 text-xs text-brand-text-secondary font-medium">
                    {r.generatedBy}
                  </td>

                  {/* Generated At */}
                  <td className="py-3.5 px-4 text-xs text-brand-text-secondary font-mono">
                    {r.generatedAt}
                  </td>

                  {/* Score */}
                  <td className="py-3.5 px-4 text-center text-xs font-black font-mono">
                    {isFailed || isProcessing ? (
                      <span className="text-brand-text-secondary/40">--</span>
                    ) : (
                      <span className={getScoreColor(r.qualityScore)}>{r.qualityScore}%</span>
                    )}
                  </td>

                  {/* Status */}
                  <td className="py-3.5 px-4">
                    {getStatusBadge(r.status)}
                  </td>

                  {/* Version */}
                  <td className="py-3.5 px-4 text-center text-xs font-mono text-brand-text-secondary font-semibold">
                    {r.version}
                  </td>

                  {/* Actions */}
                  <td className="py-3.5 px-4 text-right" onClick={(e) => e.stopPropagation()}>
                    <div className="flex items-center justify-end gap-1">
                      <button
                        onClick={() => openPreview(r)}
                        disabled={isFailed || isProcessing}
                        className="p-1.5 rounded-lg hover:bg-white/[0.06] text-brand-text-secondary hover:text-white transition-all disabled:opacity-20 disabled:cursor-not-allowed"
                        title="Preview report"
                      >
                        <Eye className="w-3.5 h-3.5" />
                      </button>
                      <button
                        onClick={() => setExportReport(r)}
                        disabled={isFailed || isProcessing}
                        className="p-1.5 rounded-lg hover:bg-white/[0.06] text-brand-text-secondary hover:text-white transition-all disabled:opacity-20 disabled:cursor-not-allowed"
                        title="Export report"
                      >
                        <Download className="w-3.5 h-3.5" />
                      </button>
                      <button
                        onClick={() => setShareReport(r)}
                        disabled={isFailed || isProcessing}
                        className="p-1.5 rounded-lg hover:bg-white/[0.06] text-brand-text-secondary hover:text-white transition-all disabled:opacity-20 disabled:cursor-not-allowed"
                        title="Share report"
                      >
                        <Share2 className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </td>
                </motion.tr>
              );
            })
          )}
        </tbody>
      </table>
    </div>
  );
}
export default ReportsTable;
